global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "user-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["user-service:8000"]

  - job_name: "order-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["order-service:8000"]
